config/routes.rb
Tgn::Application.routes.draw do
 

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :products, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: "static_pages#home"
  

  match '/signup', to: "users#new"
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/products', to: 'products#index'
  
  match '/sell', to: "static_pages#sell"
  match '/search', to: "static_pages#search"
  match '/help', to: "static_pages#help"
  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"
 

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<div class="alert alert-error">
The form contains <%= pluralize(object.errors.count, "error") %>.
</div>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li>* <%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="products">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<div class="container">
<div class="row">
  <li>
<div class="span4"><%= image_tag feed_item.pic.url(:medium) %></div>
<div class="span4"><span class="content"><h2><%= feed_item.content %></h2></span>
  <span class="content"><%=  "   Price per Kilo  ::  " %><%= feed_item.price %></span>
  <span class="content"><%=  "   Ammount Available  ::  " %><%= feed_item.ammount %></span>
  <span class="content"><%=  "   Is it Organic  ::  " %><%= feed_item.organic ? 'Yes' : 'No'  %></span>
  <span class="content"><%=  "   Can it be delivered  ::  " %><%= feed_item.delivery ? 'No' : 'Yes' %></span><span class="timestamp">
Posted <%= time_ago_in_words(feed_item.created_at) %> ago.

</span>

<% if current_user?(feed_item.user) %>
<%= link_to "delete", feed_item, method: :delete,
confirm: "You sure?",
title: feed_item.content %>
<% end %></div>
<div class="span4">
<h2>Location</h2><h3><%= feed_item.user.location %></h3>

app/views/shared/_product_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :content, placeholder: "What have you just harvested..." %>
  </div>
  <div class="field">
    <%= f.label :price %><%= f.text_field :price %>
  </div>
    <div class="field">
    <%= f.label :ammount %><%= f.text_field :ammount %>
  </div>
<div class="field">
  <%='Is it Organicly Grown?    ' %><br>
  <%= f.radio_button :organic, 'organic', :checked => true %> 
  <%= label :organic_yes, 'Yes', :style => "display:inline" %>
  <%= f.radio_button :organic, 'No', :style => "display:inline" %>
  <%= label :organic_no, 'No', :style => "display:inline" %>
</div><br>
<div style="display:inline"><div class="field">
  
  <%='Can you Deliver Locally?    ' %><br>
  <%= f.radio_button :delivery, 'Yes', :checked => true %>
  <%= label :delivery_yes, 'Yes',:style => "display:inline" %>
  <%= f.radio_button :delivery, 'No', :style => "display:inline" %>
  <%= label :delivery_no, 'No',  :style => "display:inline" %>
</div></div><br>
<p>
   <b> Picture </b><br/>
        <%= f.file_field :pic %>
  </p>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>

<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
<a href="<%= following_user_path(@user) %>">
<strong id="following" class="stat">
<%= @user.followed_users.count %>
</strong>
following
</a>
<a href="<%= followers_user_path(@user) %>">
<strong id="followers" class="stat">
<%= @user.followers.count %>
</strong>
followers
</a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">

</a>
<h1>
<%= current_user.name %>
</h1>
<span>
<%= link_to "view my profile", current_user %>
</span>
<span>
<%= pluralize(current_user.products.count, "product") %>
</span>