config/routes.rb
Tgn::Application.routes.draw do
 

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :products, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: "static_pages#home"
  

  match '/signup', to: "users#new"
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/products', to: 'products#index'
  
  match '/sell', to: "static_pages#sell"
  match '/search', to: "static_pages#search"
  match '/help', to: "static_pages#help"
  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"
 

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                 :integer         not null, primary key
#  content            :string(255)
#  user_id            :integer
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  ammount            :decimal(, )
#  price              :decimal(, )
#  organic            :boolean
#  delivery           :boolean
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  pic_file_name      :string(255)
#  pic_content_type   :string(255)
#  pic_file_size      :integer
#  pic_updated_at     :datetime
#

class Product < ActiveRecord::Base
  attr_accessible :content, :price, :ammount, :organic, :delivery, :farm_name, :pic, :pic_file_name, :pic_content_type, :pic_file_size, :pic_updated_at,
  :location, :longtitude, :latitude
  has_attached_file :pic, :styles => 
        { :medium => "300x300>", :thumb => "150x150>" }
 
  belongs_to :user
  
has_attached_file :photo,
            :url  => "/assets/products/:id/:style/:basename.:extension",
            :path => "/assets/products/:id/:style/:basename.:extension"

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 50 }

 
  
  default_scope order: 'products.created_at DESC'

def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user, only: :destroy

  def create
    @product = current_user.products.build(params[:product])
    if @product.save
      flash[:success] = "Product is on the Market!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def index
   
    @products = Product.all
  end

  def destroy
    @product.destroy
    redirect_to root_url
  end

  

  private

    def correct_user
      @product = current_user.products.find_by_id(params[:id])
      redirect_to root_url if @product.nil?
    end
end

app/helpers/products_helper.rb
module ProductsHelper
def wrap(content)
sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
end

  def description_excerpt(c)
     return unlessc
     c.split(" ")[0..4].join + "..."
   end

private
def wrap_long_string(text, max_width = 30)
zero_width_space = "&#8203;"
regex = /.{1,#{max_width}}/
(text.length < max_width) ? text :
text.scan(regex).join(zero_width_space)
end
end

app/views/products/_myproduct.html.erb
<% if current_user?(product.user) %>
<div class="container">
<div class="row">
	<li>
<div class="span4"><%= image_tag product.pic.url(:medium) %></div>
<div class="span4"><span class="content"><h2><%= product.content %></h2></span>
  <span class="content"><%=  "   Price per Kilo  ::  " %><%= product.price %></span>
  <span class="content"><%=  "   Ammount Available  ::  " %><%= product.ammount %></span>
  <span class="content"><%=  "   Is it Organic  ::  " %><%= product.organic ? 'Yes' : 'No'  %></span>
  <span class="content"><%=  "   Can it be delivered  ::  " %><%= product.delivery ? 'No' : 'Yes' %></span><span class="timestamp">
Posted <%= time_ago_in_words(product.created_at) %> ago.

</span>


<%= link_to "delete", product, method: :delete,
confirm: "You sure?",
title: product.content %>
<% end %></div>

app/views/products/_photo.html.erb
<fieldset>
    <% if !f.object.new_record? %>
        <%= image_tag f.object.data.url %>
    <% end %>
    
    <%= f.file_field :data %>
    <%= delete_photo(f) %>
</fieldset>

app/views/products/_product.html.erb
<div class="container">
<div class="row">
	<li>
<div class="span4"><%= image_tag product.pic.url(:medium) %></div>
<div class="span4"><span class="content"><h2><%= product.content %></h2></span>
  <span class="content"><%=  "   Price per Kilo  ::  " %><%= product.price %></span>
  <span class="content"><%=  "   Ammount Available  ::  " %><%= product.ammount %></span>
  <span class="content"><%=  "   Is it Organic  ::  " %><%= product.organic ? 'Yes' : 'No'  %></span>
  <span class="content"><%=  "   Can it be delivered  ::  " %><%= product.delivery ? 'No' : 'Yes' %></span><span class="timestamp">


<ul>



</ul>

Posted <%= time_ago_in_words(product.created_at) %> ago.

</span>

</div>
<% if signed_in? %>
<% if current_user?(product.user) %><br><br><br><br><br><br>
<center><%= link_to "Remove Listing", product, method: :delete,
confirm: "You sure?", title: product.content, class: "btn btn-small btn-primary"  %>
<% else %>
<div class="span4">

 <h4><%= product.user.location %></h4><h2><%= product.user.farm_name %>  </h2>
<span class="timestamp">
<% distance = Geocoder::Calculations.distance_between([product.user.latitude, product.user.longitude], [current_user.latitude,current_user.longitude],{:units => :km, :precision => 2 }) %>
<%= number_with_precision(distance, :precision => 0) %> Kilometers away from you</span>
<br><br>
	<%= link_to "Visit Farm", product.user, class: "btn btn-small btn-primary"  %>

<%= link_to "Message Farmer", users_path, class: "btn btn-small btn-primary"  %></div><% end %><% else %>

<br><br><br><br><br><br>
<center><%= link_to "Sign Up Here", signup_path, class: "btn btn-small btn-primary"  %><% end %>

</li>
</div>
</div>

app/views/products/_search.html.erb
<%= form_for product, :action => 'search', :method => 'get' do %>
     <%= text_field_tag :search, params[:search], :id => 'search_field' %>
     <%= submit_tag "Search", :name => nil %> 
     <%= link_to_function "Clear", "$('search_field').clear()" %>
<% end %> 

app/views/products/index.html.erb
<% provide(:title, 'All Produce') %>
 <form class="navbar-search pull-left">
<%= form_tag products_path, :method => :get do  %>
                                   <p>
                                         <%= text_field_tag :search  %>                              
                                   </p>
                                  <p> <class="button">
                                         <%= submit_tag "Search" %>
                                 </p>
                            <% end %>
<h1>Latest Things Harvested...</h1>

<ul class="users">
<%= render @products %>
</ul>